services:
  - type: web
    name: challenge-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_JDBC_URL
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
