quarkus.application.name=challenge-backend
quarkus.http.port=${BACKEND_PORT:8080}

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=${DATABASE_JDBC_URL:jdbc:postgresql://localhost:5432/turma_do_bem}
quarkus.datasource.username=${POSTGRES_USER:turma_admin}
quarkus.datasource.password=${POSTGRES_PASSWORD:turma_segura_2026}

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=false

quarkus.http.cors=true
quarkus.http.cors.origins=${CORS_ORIGINS:*}
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

quarkus.smallrye-openapi.path=/q/openapi
mp.openapi.extensions.smallrye.info.title=Turma do Bem Backend API
mp.openapi.extensions.smallrye.info.version=1.0.0
